#Desafio 004
n = input('Informe algo: ')
print('Tipo de dado:', type(n))
print('é digito?', n.isdigit())
print('É numerico?',n.isnumeric())
print('é alfanumérico?', n.isalnum())
print('é afabetico?', n.isalpha())
print('é decimal?', n.isdecimal())
print('é espaço?', n.isspace())
print('A string é toda maiuscula?', n.isupper())
print('A string é toda minuscula?', n.islower())
print('é valido como parametro?', n.isidentifier())
print('possui maiuscula no inicio da palavra e minuscula no corpo?', n.istitle())
print('possui caracteres imprimiveis?', n.isprintable())