print('Desafio 03')
num1=input('Primeiro valor: ')
num2=input('Segundo valor: ')
soma=int(num1)+int(num2)
subtracao=int(num1)-int(num2)
multiplicacao=int(num1)*int(num2)
divisao=int(num1)/int(num2)
resto=int(num1)%int(num2)
print('A soma é:',int(num1)+int(num2))
print('A soma é:',soma)
print('A subtração é:',subtracao)
print('A multiplicação é:',multiplicacao)
print('A divisao é:',divisao)
print('O resto é:',resto)
