print('Desafio 02')
dia=input('Informe o dia do seu nascimento: ')
mes=input('Informe o mes do seu nascimento: ')
ano=input('Informe o ano do seu nascimento: ')
print('Voce nasceu no dia',dia,'do mês',mes,'do ano de',ano,'.')
print('Data de nascimento: ',dia,'/',mes,'/',ano)
print('Você nasceu no dia ',dia,' de ',mes,' de ',ano,'. Correto?')
